# Generated by Django 3.1.4 on 2020-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Bangalore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField()),
                ('feels_like', models.TextField()),
                ('temp_min', models.TextField()),
                ('temp_max', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Chennai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField()),
                ('feels_like', models.TextField()),
                ('temp_min', models.TextField()),
                ('temp_max', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Delhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField()),
                ('feels_like', models.TextField()),
                ('temp_min', models.TextField()),
                ('temp_max', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Hyderabad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField()),
                ('feels_like', models.TextField()),
                ('temp_min', models.TextField()),
                ('temp_max', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
